// This list was created by transforming data from
// https://raw.githubusercontent.com/nshntarora/Indian-Cities-JSON/master/cities.json

const cityToState = {
  mumbai: "Maharashtra",
  delhi: "Delhi",
  bengaluru: "Karnataka",
  ahmedabad: "Gujarat",
  hyderabad: "Telangana",
  chennai: "Tamil Nadu",
  kolkata: "West Bengal",
  pune: "Maharashtra",
  jaipur: "Rajasthan",
  surat: "Gujarat",
  ghaziabad: "Uttar Pradesh",
  lucknow: "Uttar Pradesh",
  kanpur: "Uttar Pradesh",
  nagpur: "Maharashtra",
  patna: "Bihar",
  indore: "Madhya Pradesh",
  thane: "Maharashtra",
  bhopal: "Madhya Pradesh",
  visakhapatnam: "Andhra Pradesh",
  vadodara: "Gujarat",
  firozabad: "Uttar Pradesh",
  ludhiana: "Punjab",
  rajkot: "Gujarat",
  agra: "Uttar Pradesh",
  siliguri: "West Bengal",
  nashik: "Maharashtra",
  faridabad: "Haryana",
  patiala: "Punjab",
  meerut: "Uttar Pradesh",
  "kalyan-dombivali": "Maharashtra",
  "vasai-virar": "Maharashtra",
  varanasi: "Uttar Pradesh",
  srinagar: "Jammu and Kashmir",
  dhanbad: "Jharkhand",
  jodhpur: "Rajasthan",
  amritsar: "Punjab",
  raipur: "Chhattisgarh",
  allahabad: "Uttar Pradesh",
  coimbatore: "Tamil Nadu",
  jabalpur: "Madhya Pradesh",
  gwalior: "Madhya Pradesh",
  vijayawada: "Andhra Pradesh",
  madurai: "Tamil Nadu",
  guwahati: "Assam",
  chandigarh: "Haryana, Punjab",
  "hubli-dharwad": "Karnataka",
  amroha: "Uttar Pradesh",
  moradabad: "Uttar Pradesh",
  gurgaon: "Haryana",
  aligarh: "Uttar Pradesh",
  solapur: "Maharashtra",
  ranchi: "Jharkhand",
  jalandhar: "Punjab",
  tiruchirappalli: "Tamil Nadu",
  bhubaneswar: "Odisha",
  salem: "Tamil Nadu",
  warangal: "Telangana",
  "mira-bhayandar": "Maharashtra",
  thiruvananthapuram: "Kerala",
  bhiwandi: "Maharashtra",
  saharanpur: "Uttar Pradesh",
  guntur: "Andhra Pradesh",
  amravati: "Maharashtra",
  bikaner: "Rajasthan",
  noida: "Uttar Pradesh",
  jamshedpur: "Jharkhand",
  "bhilai nagar": "Chhattisgarh",
  cuttack: "Odisha",
  kochi: "Kerala",
  udaipur: "Tripura",
  bhavnagar: "Gujarat",
  dehradun: "Uttarakhand",
  asansol: "West Bengal",
  "nanded-waghala": "Maharashtra",
  ajmer: "Rajasthan",
  jamnagar: "Gujarat",
  ujjain: "Madhya Pradesh",
  sangli: "Maharashtra",
  loni: "Uttar Pradesh",
  jhansi: "Uttar Pradesh",
  pondicherry: "Puducherry",
  nellore: "Andhra Pradesh",
  jammu: "Jammu and Kashmir",
  belagavi: "Karnataka",
  raurkela: "Odisha",
  mangaluru: "Karnataka",
  tirunelveli: "Tamil Nadu",
  malegaon: "Maharashtra",
  gaya: "Bihar",
  tiruppur: "Tamil Nadu",
  davanagere: "Karnataka",
  kozhikode: "Kerala",
  akola: "Maharashtra",
  kurnool: "Andhra Pradesh",
  "bokaro steel city": "Jharkhand",
  rajahmundry: "Andhra Pradesh",
  ballari: "Karnataka",
  agartala: "Tripura",
  bhagalpur: "Bihar",
  latur: "Maharashtra",
  dhule: "Maharashtra",
  korba: "Chhattisgarh",
  bhilwara: "Rajasthan",
  brahmapur: "Odisha",
  mysore: "Karnataka",
  muzaffarpur: "Bihar",
  ahmednagar: "Maharashtra",
  kollam: "Kerala",
  raghunathganj: "West Bengal",
  bilaspur: "Chhattisgarh",
  shahjahanpur: "Uttar Pradesh",
  thrissur: "Kerala",
  alwar: "Rajasthan",
  kakinada: "Andhra Pradesh",
  nizamabad: "Telangana",
  sagar: "Madhya Pradesh",
  tumkur: "Karnataka",
  hisar: "Haryana",
  rohtak: "Haryana",
  panipat: "Haryana",
  darbhanga: "Bihar",
  kharagpur: "West Bengal",
  aizawl: "Mizoram",
  ichalkaranji: "Maharashtra",
  tirupati: "Andhra Pradesh",
  karnal: "Haryana",
  bathinda: "Punjab",
  rampur: "Uttar Pradesh",
  shivamogga: "Karnataka",
  ratlam: "Madhya Pradesh",
  modinagar: "Uttar Pradesh",
  durg: "Chhattisgarh",
  shillong: "Meghalaya",
  imphal: "Manipur",
  hapur: "Uttar Pradesh",
  ranipet: "Tamil Nadu",
  anantapur: "Andhra Pradesh",
  arrah: "Bihar",
  karimnagar: "Telangana",
  parbhani: "Maharashtra",
  etawah: "Uttar Pradesh",
  bharatpur: "Rajasthan",
  begusarai: "Bihar",
  "new delhi": "Delhi",
  chhapra: "Gujarat",
  kadapa: "Andhra Pradesh",
  ramagundam: "Telangana",
  pali: "Madhya Pradesh",
  satna: "Madhya Pradesh",
  vizianagaram: "Andhra Pradesh",
  katihar: "Bihar",
  hardwar: "Uttarakhand",
  sonipat: "Haryana",
  nagercoil: "Tamil Nadu",
  thanjavur: "Tamil Nadu",
  "murwara (katni)": "Madhya Pradesh",
  naihati: "West Bengal",
  sambhal: "Uttar Pradesh",
  nadiad: "Gujarat",
  yamunanagar: "Haryana",
  "english bazar": "West Bengal",
  eluru: "Andhra Pradesh",
  munger: "Bihar",
  panchkula: "Haryana",
  raayachuru: "Karnataka",
  panvel: "Maharashtra",
  deoghar: "Jharkhand",
  ongole: "Andhra Pradesh",
  nandyal: "Andhra Pradesh",
  morena: "Madhya Pradesh",
  bhiwani: "Haryana",
  porbandar: "Gujarat",
  palakkad: "Kerala",
  anand: "Gujarat",
  purnia: "Bihar",
  baharampur: "West Bengal",
  barmer: "Rajasthan",
  morvi: "Gujarat",
  orai: "Uttar Pradesh",
  bahraich: "Uttar Pradesh",
  sikar: "Rajasthan",
  vellore: "Tamil Nadu",
  singrauli: "Madhya Pradesh",
  khammam: "Telangana",
  mahesana: "Gujarat",
  silchar: "Assam",
  sambalpur: "Odisha",
  rewa: "Madhya Pradesh",
  unnao: "Uttar Pradesh",
  "hugli-chinsurah": "West Bengal",
  raiganj: "West Bengal",
  phusro: "Jharkhand",
  adityapur: "Jharkhand",
  alappuzha: "Kerala",
  bahadurgarh: "Haryana",
  machilipatnam: "Andhra Pradesh",
  "rae bareli": "Uttar Pradesh",
  jalpaiguri: "West Bengal",
  bharuch: "Gujarat",
  pathankot: "Punjab",
  hoshiarpur: "Punjab",
  baramula: "Jammu and Kashmir",
  adoni: "Andhra Pradesh",
  jind: "Haryana",
  tonk: "Rajasthan",
  tenali: "Andhra Pradesh",
  kancheepuram: "Tamil Nadu",
  vapi: "Gujarat",
  sirsa: "Haryana",
  navsari: "Gujarat",
  mahbubnagar: "Telangana",
  puri: "Odisha",
  "robertson pet": "Karnataka",
  erode: "Tamil Nadu",
  batala: "Punjab",
  "haldwani-cum-kathgodam": "Uttarakhand",
  vidisha: "Madhya Pradesh",
  saharsa: "Bihar",
  thanesar: "Haryana",
  chittoor: "Andhra Pradesh",
  veraval: "Gujarat",
  lakhimpur: "Uttar Pradesh",
  sitapur: "Uttar Pradesh",
  hindupur: "Andhra Pradesh",
  santipur: "West Bengal",
  balurghat: "West Bengal",
  ganjbasoda: "Madhya Pradesh",
  moga: "Punjab",
  proddatur: "Andhra Pradesh",
  medinipur: "West Bengal",
  habra: "West Bengal",
  sasaram: "Bihar",
  hajipur: "Bihar",
  bhuj: "Gujarat",
  shivpuri: "Madhya Pradesh",
  ranaghat: "West Bengal",
  shimla: "Himachal Pradesh",
  tiruvannamalai: "Tamil Nadu",
  kaithal: "Haryana",
  rajnandgaon: "Chhattisgarh",
  godhra: "Gujarat",
  hazaribag: "Jharkhand",
  bhimavaram: "Andhra Pradesh",
  mandsaur: "Madhya Pradesh",
  dibrugarh: "Assam",
  kolar: "Karnataka",
  bankura: "West Bengal",
  mandya: "Karnataka",
  "dehri-on-sone": "Bihar",
  madanapalle: "Andhra Pradesh",
  malerkotla: "Punjab",
  lalitpur: "Uttar Pradesh",
  bettiah: "Bihar",
  pollachi: "Tamil Nadu",
  khanna: "Punjab",
  neemuch: "Madhya Pradesh",
  palwal: "Haryana",
  palanpur: "Gujarat",
  guntakal: "Andhra Pradesh",
  nabadwip: "West Bengal",
  udupi: "Karnataka",
  jagdalpur: "Chhattisgarh",
  motihari: "Bihar",
  pilibhit: "Uttar Pradesh",
  dimapur: "Nagaland",
  mohali: "Punjab",
  sadulpur: "Rajasthan",
  rajapalayam: "Tamil Nadu",
  dharmavaram: "Andhra Pradesh",
  kashipur: "Uttarakhand",
  sivakasi: "Tamil Nadu",
  darjiling: "West Bengal",
  chikkamagaluru: "Karnataka",
  gudivada: "Andhra Pradesh",
  "baleshwar town": "Odisha",
  mancherial: "Telangana",
  srikakulam: "Andhra Pradesh",
  adilabad: "Telangana",
  yavatmal: "Maharashtra",
  barnala: "Punjab",
  nagaon: "Assam",
  narasaraopet: "Andhra Pradesh",
  raigarh: "Chhattisgarh",
  roorkee: "Uttarakhand",
  valsad: "Gujarat",
  ambikapur: "Chhattisgarh",
  giridih: "Jharkhand",
  chandausi: "Uttar Pradesh",
  purulia: "West Bengal",
  patan: "Gujarat",
  bagaha: "Bihar",
  "hardoi ": "Uttar Pradesh",
  achalpur: "Maharashtra",
  osmanabad: "Maharashtra",
  deesa: "Gujarat",
  nandurbar: "Maharashtra",
  azamgarh: "Uttar Pradesh",
  ramgarh: "Jharkhand",
  firozpur: "Punjab",
  "baripada town": "Odisha",
  karwar: "Karnataka",
  siwan: "Bihar",
  rajampet: "Andhra Pradesh",
  pudukkottai: "Tamil Nadu",
  anantnag: "Jammu and Kashmir",
  tadpatri: "Andhra Pradesh",
  satara: "Maharashtra",
  bhadrak: "Odisha",
  kishanganj: "Bihar",
  suryapet: "Telangana",
  wardha: "Maharashtra",
  ranebennuru: "Karnataka",
  amreli: "Gujarat",
  "neyveli (ts)": "Tamil Nadu",
  jamalpur: "Bihar",
  marmagao: "Goa",
  udgir: "Maharashtra",
  tadepalligudem: "Andhra Pradesh",
  nagapattinam: "Tamil Nadu",
  buxar: "Bihar",
  aurangabad: "Bihar",
  jehanabad: "Bihar",
  phagwara: "Punjab",
  khair: "Uttar Pradesh",
  "sawai madhopur": "Rajasthan",
  kapurthala: "Punjab",
  chilakaluripet: "Andhra Pradesh",
  malappuram: "Kerala",
  rewari: "Haryana",
  nagaur: "Rajasthan",
  sultanpur: "Uttar Pradesh",
  nagda: "Madhya Pradesh",
  "port blair": "Andaman and Nicobar Islands",
  lakhisarai: "Bihar",
  panaji: "Goa",
  tinsukia: "Assam",
  itarsi: "Madhya Pradesh",
  kohima: "Nagaland",
  balangir: "Odisha",
  nawada: "Bihar",
  jharsuguda: "Odisha",
  jagtial: "Telangana",
  viluppuram: "Tamil Nadu",
  amalner: "Maharashtra",
  zirakpur: "Punjab",
  tanda: "Uttar Pradesh",
  tiruchengode: "Tamil Nadu",
  nagina: "Uttar Pradesh",
  yemmiganur: "Andhra Pradesh",
  vaniyambadi: "Tamil Nadu",
  sarni: "Madhya Pradesh",
  "theni allinagaram": "Tamil Nadu",
  margao: "Goa",
  akot: "Maharashtra",
  sehore: "Madhya Pradesh",
  "mhow cantonment": "Madhya Pradesh",
  "kot kapura": "Punjab",
  makrana: "Rajasthan",
  pandharpur: "Maharashtra",
  miryalaguda: "Telangana",
  shamli: "Uttar Pradesh",
  seoni: "Madhya Pradesh",
  ranibennur: "Karnataka",
  kadiri: "Andhra Pradesh",
  shrirampur: "Maharashtra",
  rudrapur: "Uttar Pradesh",
  parli: "Maharashtra",
  najibabad: "Uttar Pradesh",
  nirmal: "Telangana",
  udhagamandalam: "Tamil Nadu",
  shikohabad: "Uttar Pradesh",
  "jhumri tilaiya": "Jharkhand",
  aruppukkottai: "Tamil Nadu",
  ponnani: "Kerala",
  jamui: "Bihar",
  sitamarhi: "Bihar",
  chirala: "Andhra Pradesh",
  anjar: "Gujarat",
  karaikal: "Puducherry",
  hansi: "Haryana",
  anakapalle: "Andhra Pradesh",
  mahasamund: "Chhattisgarh",
  faridkot: "Punjab",
  saunda: "Jharkhand",
  dhoraji: "Gujarat",
  paramakudi: "Tamil Nadu",
  balaghat: "Madhya Pradesh",
  sujangarh: "Rajasthan",
  khambhat: "Gujarat",
  muktsar: "Punjab",
  rajpura: "Punjab",
  kavali: "Andhra Pradesh",
  dhamtari: "Chhattisgarh",
  "ashok nagar": "Madhya Pradesh",
  sardarshahar: "Rajasthan",
  mahuva: "Gujarat",
  bargarh: "Odisha",
  kamareddy: "Telangana",
  sahibganj: "Jharkhand",
  kothagudem: "Telangana",
  ramanagaram: "Karnataka",
  gokak: "Karnataka",
  tikamgarh: "Madhya Pradesh",
  araria: "Bihar",
  rishikesh: "Uttarakhand",
  shahdol: "Madhya Pradesh",
  "medininagar (daltonganj)": "Jharkhand",
  arakkonam: "Tamil Nadu",
  washim: "Maharashtra",
  sangrur: "Punjab",
  bodhan: "Telangana",
  fazilka: "Punjab",
  palacole: "Andhra Pradesh",
  keshod: "Gujarat",
  sullurpeta: "Andhra Pradesh",
  wadhwan: "Gujarat",
  gurdaspur: "Punjab",
  vatakara: "Kerala",
  tura: "Meghalaya",
  narnaul: "Haryana",
  kharar: "Punjab",
  yadgir: "Karnataka",
  ambejogai: "Maharashtra",
  ankleshwar: "Gujarat",
  savarkundla: "Gujarat",
  paradip: "Odisha",
  virudhachalam: "Tamil Nadu",
  kanhangad: "Kerala",
  kadi: "Gujarat",
  srivilliputhur: "Tamil Nadu",
  gobindgarh: "Punjab",
  tindivanam: "Tamil Nadu",
  mansa: "Gujarat",
  taliparamba: "Kerala",
  manmad: "Maharashtra",
  tanuku: "Andhra Pradesh",
  rayachoti: "Andhra Pradesh",
  virudhunagar: "Tamil Nadu",
  koyilandy: "Kerala",
  jorhat: "Assam",
  karur: "Tamil Nadu",
  valparai: "Tamil Nadu",
  srikalahasti: "Andhra Pradesh",
  neyyattinkara: "Kerala",
  bapatla: "Andhra Pradesh",
  fatehabad: "Haryana",
  malout: "Punjab",
  sankarankovil: "Tamil Nadu",
  tenkasi: "Tamil Nadu",
  ratnagiri: "Maharashtra",
  "rabkavi banhatti": "Karnataka",
  sikandrabad: "Uttar Pradesh",
  chaibasa: "Jharkhand",
  chirmiri: "Chhattisgarh",
  palwancha: "Telangana",
  bhawanipatna: "Odisha",
  kayamkulam: "Kerala",
  pithampur: "Madhya Pradesh",
  nabha: "Punjab",
  "shahabad, hardoi": "Uttar Pradesh",
  dhenkanal: "Odisha",
  "uran islampur": "Maharashtra",
  gopalganj: "Bihar",
  "bongaigaon city": "Assam",
  palani: "Tamil Nadu",
  pusad: "Maharashtra",
  sopore: "Jammu and Kashmir",
  pilkhuwa: "Uttar Pradesh",
  "tarn taran": "Punjab",
  renukoot: "Uttar Pradesh",
  mandamarri: "Telangana",
  shahabad: "Karnataka",
  barbil: "Odisha",
  koratla: "Telangana",
  madhubani: "Bihar",
  arambagh: "West Bengal",
  gohana: "Haryana",
  ladnu: "Rajasthan",
  pattukkottai: "Tamil Nadu",
  sirsi: "Uttar Pradesh",
  sircilla: "Telangana",
  tamluk: "West Bengal",
  jagraon: "Punjab",
  "alipurdurban agglomerationr": "West Bengal",
  alirajpur: "Madhya Pradesh",
  tandur: "Telangana",
  naidupet: "Andhra Pradesh",
  tirupathur: "Tamil Nadu",
  tohana: "Haryana",
  ratangarh: "Rajasthan",
  dhubri: "Assam",
  masaurhi: "Bihar",
  visnagar: "Gujarat",
  vrindavan: "Uttar Pradesh",
  nokha: "Bihar",
  nagari: "Andhra Pradesh",
  narwana: "Haryana",
  ramanathapuram: "Tamil Nadu",
  ujhani: "Uttar Pradesh",
  samastipur: "Bihar",
  laharpur: "Uttar Pradesh",
  sangamner: "Maharashtra",
  nimbahera: "Rajasthan",
  siddipet: "Telangana",
  suri: "West Bengal",
  diphu: "Assam",
  jhargram: "West Bengal",
  "shirpur-warwade": "Maharashtra",
  tilhar: "Uttar Pradesh",
  sindhnur: "Karnataka",
  udumalaipettai: "Tamil Nadu",
  malkapur: "Maharashtra",
  wanaparthy: "Telangana",
  gudur: "Andhra Pradesh",
  kendujhar: "Odisha",
  mandla: "Madhya Pradesh",
  mandi: "Himachal Pradesh",
  nedumangad: "Kerala",
  "north lakhimpur": "Assam",
  vinukonda: "Andhra Pradesh",
  tiptur: "Karnataka",
  gobichettipalayam: "Tamil Nadu",
  sunabeda: "Odisha",
  wani: "Maharashtra",
  upleta: "Gujarat",
  narasapuram: "Andhra Pradesh",
  nuzvid: "Andhra Pradesh",
  tezpur: "Assam",
  una: "Gujarat",
  markapur: "Andhra Pradesh",
  sheopur: "Madhya Pradesh",
  thiruvarur: "Tamil Nadu",
  sidhpur: "Gujarat",
  sahaswan: "Uttar Pradesh",
  suratgarh: "Rajasthan",
  shajapur: "Madhya Pradesh",
  rayagada: "Odisha",
  lonavla: "Maharashtra",
  ponnur: "Andhra Pradesh",
  kagaznagar: "Telangana",
  gadwal: "Telangana",
  bhatapara: "Chhattisgarh",
  kandukur: "Andhra Pradesh",
  sangareddy: "Telangana",
  unjha: "Gujarat",
  lunglei: "Mizoram",
  karimganj: "Assam",
  kannur: "Kerala",
  bobbili: "Andhra Pradesh",
  mokameh: "Bihar",
  "talegaon dabhade": "Maharashtra",
  anjangaon: "Maharashtra",
  mangrol: "Rajasthan",
  sunam: "Punjab",
  gangarampur: "West Bengal",
  thiruvallur: "Tamil Nadu",
  tirur: "Kerala",
  rath: "Uttar Pradesh",
  jatani: "Odisha",
  viramgam: "Gujarat",
  rajsamand: "Rajasthan",
  yanam: "Puducherry",
  kottayam: "Kerala",
  panruti: "Tamil Nadu",
  dhuri: "Punjab",
  namakkal: "Tamil Nadu",
  kasaragod: "Kerala",
  modasa: "Gujarat",
  rayadurg: "Andhra Pradesh",
  supaul: "Bihar",
  kunnamkulam: "Kerala",
  umred: "Maharashtra",
  bellampalle: "Telangana",
  sibsagar: "Assam",
  "mandi dabwali": "Haryana",
  ottappalam: "Kerala",
  dumraon: "Bihar",
  samalkot: "Andhra Pradesh",
  jaggaiahpet: "Andhra Pradesh",
  goalpara: "Assam",
  tuni: "Andhra Pradesh",
  lachhmangarh: "Rajasthan",
  bhongir: "Telangana",
  amalapuram: "Andhra Pradesh",
  "firozpur cantt.": "Punjab",
  vikarabad: "Telangana",
  thiruvalla: "Kerala",
  sherkot: "Uttar Pradesh",
  palghar: "Maharashtra",
  shegaon: "Maharashtra",
  jangaon: "Telangana",
  bheemunipatnam: "Andhra Pradesh",
  panna: "Madhya Pradesh",
  thodupuzha: "Kerala",
  "kathurban agglomeration": "Jammu and Kashmir",
  palitana: "Gujarat",
  arwal: "Bihar",
  venkatagiri: "Andhra Pradesh",
  kalpi: "Uttar Pradesh",
  "rajgarh (churu)": "Rajasthan",
  sattenapalle: "Andhra Pradesh",
  arsikere: "Karnataka",
  ozar: "Maharashtra",
  thirumangalam: "Tamil Nadu",
  petlad: "Gujarat",
  nasirabad: "Rajasthan",
  phaltan: "Maharashtra",
  rampurhat: "West Bengal",
  nanjangud: "Karnataka",
  forbesganj: "Bihar",
  tundla: "Uttar Pradesh",
  "bhaburban agglomeration": "Bihar",
  sagara: "Karnataka",
  pithapuram: "Andhra Pradesh",
  sira: "Karnataka",
  bhadrachalam: "Telangana",
  "charkhi dadri": "Haryana",
  chatra: "Jharkhand",
  "palasa kasibugga": "Andhra Pradesh",
  nohar: "Rajasthan",
  yevla: "Maharashtra",
  "sirhind fatehgarh sahib": "Punjab",
  bhainsa: "Telangana",
  parvathipuram: "Andhra Pradesh",
  shahade: "Maharashtra",
  chalakudy: "Kerala",
  narkatiaganj: "Bihar",
  kapadvanj: "Gujarat",
  macherla: "Andhra Pradesh",
  "raghogarh-vijaypur": "Madhya Pradesh",
  rupnagar: "Punjab",
  naugachhia: "Bihar",
  sendhwa: "Madhya Pradesh",
  byasanagar: "Odisha",
  sandila: "Uttar Pradesh",
  gooty: "Andhra Pradesh",
  salur: "Andhra Pradesh",
  nanpara: "Uttar Pradesh",
  sardhana: "Uttar Pradesh",
  vita: "Maharashtra",
  gumia: "Jharkhand",
  puttur: "Andhra Pradesh",
  "jalandhar cantt.": "Punjab",
  nehtaur: "Uttar Pradesh",
  changanassery: "Kerala",
  mandapeta: "Andhra Pradesh",
  dumka: "Jharkhand",
  seohara: "Uttar Pradesh",
  umarkhed: "Maharashtra",
  madhupur: "Jharkhand",
  vikramasingapuram: "Tamil Nadu",
  punalur: "Kerala",
  kendrapara: "Odisha",
  sihor: "Gujarat",
  nellikuppam: "Tamil Nadu",
  samana: "Punjab",
  warora: "Maharashtra",
  nilambur: "Kerala",
  rasipuram: "Tamil Nadu",
  ramnagar: "Bihar",
  jammalamadugu: "Andhra Pradesh",
  nawanshahr: "Punjab",
  thoubal: "Manipur",
  athni: "Karnataka",
  cherthala: "Kerala",
  sidhi: "Madhya Pradesh",
  farooqnagar: "Telangana",
  peddapuram: "Andhra Pradesh",
  chirkunda: "Jharkhand",
  pachora: "Maharashtra",
  madhepura: "Bihar",
  pithoragarh: "Uttarakhand",
  tumsar: "Maharashtra",
  phalodi: "Rajasthan",
  tiruttani: "Tamil Nadu",
  "rampura phul": "Punjab",
  perinthalmanna: "Kerala",
  padrauna: "Uttar Pradesh",
  pipariya: "Madhya Pradesh",
  "dalli-rajhara": "Chhattisgarh",
  punganur: "Andhra Pradesh",
  mattannur: "Kerala",
  mathura: "Uttar Pradesh",
  thakurdwara: "Uttar Pradesh",
  "nandivaram-guduvancheri": "Tamil Nadu",
  mulbagal: "Karnataka",
  manjlegaon: "Maharashtra",
  wankaner: "Gujarat",
  sillod: "Maharashtra",
  nidadavole: "Andhra Pradesh",
  surapura: "Karnataka",
  rajagangapur: "Odisha",
  sheikhpura: "Bihar",
  parlakhemundi: "Odisha",
  kalimpong: "West Bengal",
  siruguppa: "Karnataka",
  arvi: "Maharashtra",
  limbdi: "Gujarat",
  barpeta: "Assam",
  manglaur: "Uttarakhand",
  repalle: "Andhra Pradesh",
  mudhol: "Karnataka",
  shujalpur: "Madhya Pradesh",
  mandvi: "Gujarat",
  thangadh: "Gujarat",
  sironj: "Madhya Pradesh",
  nandura: "Maharashtra",
  shoranur: "Kerala",
  nathdwara: "Rajasthan",
  periyakulam: "Tamil Nadu",
  sultanganj: "Bihar",
  medak: "Telangana",
  narayanpet: "Telangana",
  "raxaul bazar": "Bihar",
  rajauri: "Jammu and Kashmir",
  pernampattu: "Tamil Nadu",
  nainital: "Uttarakhand",
  ramachandrapuram: "Andhra Pradesh",
  vaijapur: "Maharashtra",
  nangal: "Punjab",
  sidlaghatta: "Karnataka",
  punch: "Jammu and Kashmir",
  pandhurna: "Madhya Pradesh",
  "wadgaon road": "Maharashtra",
  talcher: "Odisha",
  varkala: "Kerala",
  pilani: "Rajasthan",
  nowgong: "Madhya Pradesh",
  "naila janjgir": "Chhattisgarh",
  mapusa: "Goa",
  vellakoil: "Tamil Nadu",
  "merta city": "Rajasthan",
  sivaganga: "Tamil Nadu",
  mandideep: "Madhya Pradesh",
  sailu: "Maharashtra",
  vyara: "Gujarat",
  kovvur: "Andhra Pradesh",
  vadalur: "Tamil Nadu",
  nawabganj: "Uttar Pradesh",
  padra: "Gujarat",
  sainthia: "West Bengal",
  siana: "Uttar Pradesh",
  shahpur: "Karnataka",
  sojat: "Rajasthan",
  noorpur: "Uttar Pradesh",
  paravoor: "Kerala",
  murtijapur: "Maharashtra",
  sundargarh: "Odisha",
  taki: "West Bengal",
  "saundatti-yellamma": "Karnataka",
  pathanamthitta: "Kerala",
  wadi: "Karnataka",
  rameshwaram: "Tamil Nadu",
  tasgaon: "Maharashtra",
  "sikandra rao": "Uttar Pradesh",
  sihora: "Madhya Pradesh",
  tiruvethipuram: "Tamil Nadu",
  tiruvuru: "Andhra Pradesh",
  mehkar: "Maharashtra",
  peringathur: "Kerala",
  perambalur: "Tamil Nadu",
  manvi: "Karnataka",
  zunheboto: "Nagaland",
  "mahnar bazar": "Bihar",
  attingal: "Kerala",
  shahbad: "Haryana",
  puranpur: "Uttar Pradesh",
  nelamangala: "Karnataka",
  nakodar: "Punjab",
  lunawada: "Gujarat",
  murshidabad: "West Bengal",
  mahe: "Puducherry",
  lanka: "Assam",
  rudauli: "Uttar Pradesh",
  tuensang: "Nagaland",
  lakshmeshwar: "Karnataka",
  zira: "Punjab",
  yawal: "Maharashtra",
  "thana bhawan": "Uttar Pradesh",
  ramdurg: "Karnataka",
  pulgaon: "Maharashtra",
  sadasivpet: "Telangana",
  nargund: "Karnataka",
  "neem-ka-thana": "Rajasthan",
  memari: "West Bengal",
  nilanga: "Maharashtra",
  naharlagun: "Arunachal Pradesh",
  pakaur: "Jharkhand",
  wai: "Maharashtra",
  tarikere: "Karnataka",
  malavalli: "Karnataka",
  raisen: "Madhya Pradesh",
  lahar: "Madhya Pradesh",
  uravakonda: "Andhra Pradesh",
  savanur: "Karnataka",
  sirohi: "Rajasthan",
  udhampur: "Jammu and Kashmir",
  umarga: "Maharashtra",
  pratapgarh: "Tripura",
  lingsugur: "Karnataka",
  usilampatti: "Tamil Nadu",
  "palia kalan": "Uttar Pradesh",
  wokha: "Nagaland",
  rajpipla: "Gujarat",
  vijayapura: "Karnataka",
  rawatbhata: "Rajasthan",
  sangaria: "Rajasthan",
  paithan: "Maharashtra",
  rahuri: "Maharashtra",
  patti: "Punjab",
  zaidpur: "Uttar Pradesh",
  lalsot: "Rajasthan",
  maihar: "Madhya Pradesh",
  vedaranyam: "Tamil Nadu",
  nawapur: "Maharashtra",
  solan: "Himachal Pradesh",
  sanawad: "Madhya Pradesh",
  warisaliganj: "Bihar",
  revelganj: "Bihar",
  sabalgarh: "Madhya Pradesh",
  tuljapur: "Maharashtra",
  simdega: "Jharkhand",
  musabani: "Jharkhand",
  kodungallur: "Kerala",
  phulabani: "Odisha",
  umreth: "Gujarat",
  narsipatnam: "Andhra Pradesh",
  nautanwa: "Uttar Pradesh",
  rajgir: "Bihar",
  yellandu: "Telangana",
  sathyamangalam: "Tamil Nadu",
  pilibanga: "Rajasthan",
  morshi: "Maharashtra",
  pehowa: "Haryana",
  sonepur: "Bihar",
  pappinisseri: "Kerala",
  zamania: "Uttar Pradesh",
  mihijam: "Jharkhand",
  purna: "Maharashtra",
  puliyankudi: "Tamil Nadu",
  "shikarpur, bulandshahr": "Uttar Pradesh",
  umaria: "Madhya Pradesh",
  porsa: "Madhya Pradesh",
  "naugawan sadat": "Uttar Pradesh",
  "fatehpur sikri": "Uttar Pradesh",
  manuguru: "Telangana",
  "pipar city": "Rajasthan",
  pattamundai: "Odisha",
  nanjikottai: "Tamil Nadu",
  taranagar: "Rajasthan",
  yerraguntla: "Andhra Pradesh",
  satana: "Maharashtra",
  sherghati: "Bihar",
  sankeshwara: "Karnataka",
  madikeri: "Karnataka",
  thuraiyur: "Tamil Nadu",
  sanand: "Gujarat",
  rajula: "Gujarat",
  kyathampalle: "Telangana",
  "shahabad, rampur": "Uttar Pradesh",
  "tilda newra": "Chhattisgarh",
  narsinghgarh: "Madhya Pradesh",
  "chittur-thathamangalam": "Kerala",
  "malaj khand": "Madhya Pradesh",
  sarangpur: "Madhya Pradesh",
  robertsganj: "Uttar Pradesh",
  sirkali: "Tamil Nadu",
  radhanpur: "Gujarat",
  tiruchendur: "Tamil Nadu",
  utraula: "Uttar Pradesh",
  patratu: "Jharkhand",
  "vijainagar, ajmer": "Rajasthan",
  periyasemur: "Tamil Nadu",
  pathri: "Maharashtra",
  sadabad: "Uttar Pradesh",
  talikota: "Karnataka",
  sinnar: "Maharashtra",
  mungeli: "Chhattisgarh",
  sedam: "Karnataka",
  shikaripur: "Karnataka",
  sumerpur: "Uttar Pradesh",
  sattur: "Tamil Nadu",
  sugauli: "Bihar",
  lumding: "Assam",
  vandavasi: "Tamil Nadu",
  titlagarh: "Odisha",
  uchgaon: "Maharashtra",
  mokokchung: "Nagaland",
  "paschim punropara": "West Bengal",
  sagwara: "Rajasthan",
  "ramganj mandi": "Rajasthan",
  tarakeswar: "West Bengal",
  mahalingapura: "Karnataka",
  dharmanagar: "Tripura",
  mahemdabad: "Gujarat",
  manendragarh: "Chhattisgarh",
  uran: "Maharashtra",
  tharamangalam: "Tamil Nadu",
  tirukkoyilur: "Tamil Nadu",
  pen: "Maharashtra",
  makhdumpur: "Bihar",
  maner: "Bihar",
  oddanchatram: "Tamil Nadu",
  palladam: "Tamil Nadu",
  mundi: "Madhya Pradesh",
  nabarangapur: "Odisha",
  mudalagi: "Karnataka",
  samalkha: "Haryana",
  nepanagar: "Madhya Pradesh",
  karjat: "Maharashtra",
  ranavav: "Gujarat",
  pedana: "Andhra Pradesh",
  pinjore: "Haryana",
  lakheri: "Rajasthan",
  pasan: "Madhya Pradesh",
  vadakkuvalliyur: "Tamil Nadu",
  tirukalukundram: "Tamil Nadu",
  mahidpur: "Madhya Pradesh",
  mussoorie: "Uttarakhand",
  muvattupuzha: "Kerala",
  rasra: "Uttar Pradesh",
  udaipurwati: "Rajasthan",
  manwath: "Maharashtra",
  adoor: "Kerala",
  uthamapalayam: "Tamil Nadu",
  partur: "Maharashtra",
  nahan: "Himachal Pradesh",
  ladwa: "Haryana",
  mankachar: "Assam",
  nongstoin: "Meghalaya",
  losal: "Rajasthan",
  "sri madhopur": "Rajasthan",
  ramngarh: "Rajasthan",
  mavelikkara: "Kerala",
  rawatsar: "Rajasthan",
  rajakhera: "Rajasthan",
  lar: "Uttar Pradesh",
  "lal gopalganj nindaura": "Uttar Pradesh",
  muddebihal: "Karnataka",
  sirsaganj: "Uttar Pradesh",
  shahpura: "Rajasthan",
  surandai: "Tamil Nadu",
  sangole: "Maharashtra",
  pavagada: "Karnataka",
  tharad: "Gujarat",
  umbergaon: "Gujarat",
  mavoor: "Kerala",
  nalbari: "Assam",
  talaja: "Gujarat",
  malur: "Karnataka",
  mangrulpir: "Maharashtra",
  soro: "Odisha",
  vadnagar: "Gujarat",
  raisinghnagar: "Rajasthan",
  sindhagi: "Karnataka",
  sanduru: "Karnataka",
  sohna: "Haryana",
  manavadar: "Gujarat",
  pihani: "Uttar Pradesh",
  safidon: "Haryana",
  risod: "Maharashtra",
  rosera: "Bihar",
  sankari: "Tamil Nadu",
  malpura: "Rajasthan",
  sonamukhi: "West Bengal",
  "shamsabad, agra": "Uttar Pradesh",
  "pandurban agglomeration": "West Bengal",
  mainaguri: "West Bengal",
  afzalpur: "Karnataka",
  shirur: "Maharashtra",
  salaya: "Gujarat",
  shenkottai: "Tamil Nadu",
  vadipatti: "Tamil Nadu",
  nagarkurnool: "Telangana",
  savner: "Maharashtra",
  sasvad: "Maharashtra",
  soron: "Uttar Pradesh",
  sholingur: "Tamil Nadu",
  pandharkaoda: "Maharashtra",
  perumbavoor: "Kerala",
  maddur: "Karnataka",
  nadbai: "Rajasthan",
  talode: "Maharashtra",
  shrigonda: "Maharashtra",
  madhugiri: "Karnataka",
  tekkalakote: "Karnataka",
  "seoni-malwa": "Madhya Pradesh",
  shirdi: "Maharashtra",
  "surban agglomerationr": "Uttar Pradesh",
  terdal: "Karnataka",
  raver: "Maharashtra",
  taraori: "Haryana",
  mukhed: "Maharashtra",
  manachanallur: "Tamil Nadu",
  rehli: "Madhya Pradesh",
  sanchore: "Rajasthan",
  rajura: "Maharashtra",
  piro: "Bihar",
  mudabidri: "Karnataka",
  "vadgaon kasba": "Maharashtra",
  nagar: "Rajasthan",
  vijapur: "Gujarat",
  viswanatham: "Tamil Nadu",
  polur: "Tamil Nadu",
  panagudi: "Tamil Nadu",
  manawar: "Madhya Pradesh",
  tehri: "Uttarakhand",
  samdhan: "Uttar Pradesh",
  pardi: "Gujarat",
  rahatgarh: "Madhya Pradesh",
  panagar: "Madhya Pradesh",
  uthiramerur: "Tamil Nadu",
  tirora: "Maharashtra",
  rangia: "Assam",
  sahjanwa: "Uttar Pradesh",
  "wara seoni": "Madhya Pradesh",
  magadi: "Karnataka",
  "rajgarh (alwar)": "Rajasthan",
  rafiganj: "Bihar",
  tarana: "Madhya Pradesh",
  "rampur maniharan": "Uttar Pradesh",
  sheoganj: "Rajasthan",
  raikot: "Punjab",
  pauri: "Uttarakhand",
  navalgund: "Karnataka",
  shahganj: "Uttar Pradesh",
  marhaura: "Bihar",
  tulsipur: "Uttar Pradesh",
  sadri: "Rajasthan",
  thiruthuraipoondi: "Tamil Nadu",
  shiggaon: "Karnataka",
  pallapatti: "Tamil Nadu",
  mahendragarh: "Haryana",
  sausar: "Madhya Pradesh",
  ponneri: "Tamil Nadu",
  mahad: "Maharashtra",
  lohardaga: "Jharkhand",
  tirwaganj: "Uttar Pradesh",
  margherita: "Assam",
  sundarnagar: "Himachal Pradesh",
  rajgarh: "Madhya Pradesh",
  mangaldoi: "Assam",
  renigunta: "Andhra Pradesh",
  longowal: "Punjab",
  ratia: "Haryana",
  lalgudi: "Tamil Nadu",
  shrirangapattana: "Karnataka",
  niwari: "Madhya Pradesh",
  natham: "Tamil Nadu",
  unnamalaikadai: "Tamil Nadu",
  "purqurban agglomerationzi": "Uttar Pradesh",
  "shamsabad, farrukhabad": "Uttar Pradesh",
  mirganj: "Bihar",
  todaraisingh: "Rajasthan",
  warhapur: "Uttar Pradesh",
  rajam: "Andhra Pradesh",
  "urmar tanda": "Punjab",
  lonar: "Maharashtra",
  powayan: "Uttar Pradesh",
  "p.n.patti": "Tamil Nadu",
  palampur: "Himachal Pradesh",
  "srisailam project (right flank colony) township": "Andhra Pradesh",
  sindagi: "Karnataka",
  sandi: "Uttar Pradesh",
  vaikom: "Kerala",
  malda: "West Bengal",
  tharangambadi: "Tamil Nadu",
  sakaleshapura: "Karnataka",
  lalganj: "Uttar Pradesh",
  malkangiri: "Odisha",
  rapar: "Gujarat",
  mauganj: "Madhya Pradesh",
  todabhim: "Rajasthan",
  srinivaspur: "Karnataka",
  murliganj: "Bihar",
  reengus: "Rajasthan",
  sawantwadi: "Maharashtra",
  tittakudi: "Tamil Nadu",
  lilong: "Manipur",
  rajaldesar: "Rajasthan",
  pathardi: "Maharashtra",
  achhnera: "Uttar Pradesh",
  pacode: "Tamil Nadu",
  naraura: "Uttar Pradesh",
  nakur: "Uttar Pradesh",
  palai: "Kerala",
  "morinda, india": "Punjab",
  manasa: "Madhya Pradesh",
  nainpur: "Madhya Pradesh",
  sahaspur: "Uttar Pradesh",
  pauni: "Maharashtra",
  prithvipur: "Madhya Pradesh",
  ramtek: "Maharashtra",
  silapathar: "Assam",
  songadh: "Gujarat",
  safipur: "Uttar Pradesh",
  sohagpur: "Madhya Pradesh",
  mul: "Maharashtra",
  sadulshahar: "Rajasthan",
  phillaur: "Punjab",
  sambhar: "Rajasthan",
  prantij: "Rajasthan",
  nagla: "Uttarakhand",
  pattran: "Punjab",
  "mount abu": "Rajasthan",
  reoti: "Uttar Pradesh",
  "tenu dam-cum-kathhara": "Jharkhand",
  panchla: "West Bengal",
  sitarganj: "Uttarakhand",
  pasighat: "Arunachal Pradesh",
  motipur: "Bihar",
  "o' valley": "Tamil Nadu",
  raghunathpur: "West Bengal",
  suriyampalayam: "Tamil Nadu",
  qadian: "Punjab",
  rairangpur: "Odisha",
  silvassa: "Dadra and Nagar Haveli",
  "nowrozabad (khodargama)": "Madhya Pradesh",
  soyagaon: "Maharashtra",
  sujanpur: "Punjab",
  manihari: "Bihar",
  sikanderpur: "Uttar Pradesh",
  mangalvedhe: "Maharashtra",
  phulera: "Rajasthan",
  ron: "Karnataka",
  sholavandan: "Tamil Nadu",
  saidpur: "Uttar Pradesh",
  shamgarh: "Madhya Pradesh",
  thammampatti: "Tamil Nadu",
  maharajpur: "Madhya Pradesh",
  multai: "Madhya Pradesh",
  mukerian: "Punjab",
  purwa: "Uttar Pradesh",
  sheohar: "Bihar",
  namagiripettai: "Tamil Nadu",
  parasi: "Uttar Pradesh",
  lathi: "Gujarat",
  narkhed: "Maharashtra",
  mathabhanga: "West Bengal",
  shendurjana: "Maharashtra",
  peravurani: "Tamil Nadu",
  mariani: "Assam",
  phulpur: "Uttar Pradesh",
  rania: "Haryana",
  pachore: "Madhya Pradesh",
  parangipettai: "Tamil Nadu",
  pudupattinam: "Tamil Nadu",
  panniyannur: "Kerala",
  maharajganj: "Bihar",
  rau: "Madhya Pradesh",
  monoharpur: "West Bengal",
  mandawa: "Rajasthan",
  marigaon: "Assam",
  pallikonda: "Tamil Nadu",
  pindwara: "Rajasthan",
  shishgarh: "Uttar Pradesh",
  patur: "Maharashtra",
  "mayang imphal": "Manipur",
  mhowgaon: "Madhya Pradesh",
  guruvayoor: "Kerala",
  mhaswad: "Maharashtra",
  sahawar: "Uttar Pradesh",
  sivagiri: "Tamil Nadu",
  mundargi: "Karnataka",
  punjaipugalur: "Tamil Nadu",
  kailasahar: "Tripura",
  samthar: "Uttar Pradesh",
  sakti: "Chhattisgarh",
  sadalagi: "Karnataka",
  silao: "Bihar",
  mandalgarh: "Rajasthan",
  loha: "Maharashtra",
  pukhrayan: "Uttar Pradesh",
  padmanabhapuram: "Tamil Nadu",
  belonia: "Tripura",
  saiha: "Mizoram",
  srirampore: "West Bengal",
  talwara: "Punjab",
  puthuppally: "Kerala",
  khowai: "Tripura",
  vijaypur: "Madhya Pradesh",
  takhatgarh: "Rajasthan",
  thirupuvanam: "Tamil Nadu",
  adra: "West Bengal",
  piriyapatna: "Karnataka",
  obra: "Uttar Pradesh",
  adalaj: "Gujarat",
  nandgaon: "Maharashtra",
  barh: "Bihar",
  panamattom: "Kerala",
  niwai: "Uttar Pradesh",
  bageshwar: "Uttarakhand",
  tarbha: "Odisha",
  adyar: "Karnataka",
  warud: "Maharashtra",
  asarganj: "Bihar",
  sarsod: "Haryana",
  gandhinagar: "Gujarat",
  kullu: "Himachal Pradesh",
  manali: "Himachal Praddesh",
  mirzapur: "Uttar Pradesh",
  kota: "Rajasthan",
  dispur: "Assam",
};

export { cityToState };
